include:
  - board: nice_nano//zmk
    shield: galpanel
    artifact-name: galpanel
  - board: nice_nano//zmk
    shield: galpanel_led_test
    artifact-name: galpanel-led-test
  - board: nice_nano//zmk
    shield: galpanel_led_ind_test
    artifact-name: galpanel-led-ind-test
  - board: nice_nano//zmk
    shield: galpanel_io_test
    artifact-name: galpanel-io-test
  - board: nice_nano//zmk
    shield: galpanel_ec11_test
    artifact-name: galpanel-ec11-test
  - board: nice_nano//zmk
    shield: galpanel_ble_recovery
    artifact-name: galpanel-ble-recovery
  - board: nice_nano//zmk
    shield: galpanel_status_test
    artifact-name: galpanel-status-test
  - board: nice_nano//zmk
    shield: galpanel_safety_test
    artifact-name: galpanel-safety-test
