# GALPANEL status indicator test
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_SLEEP=n
CONFIG_GALPANEL_STATUS_INDICATORS=y
CONFIG_GALPANEL_LINK_ON_MS=0
CONFIG_GALPANEL_PROFILE_NAMES=y
